# Project information
site_name: Ehoney欺骗防御系统
site_description: www.seccome.com
site_author: licheng
docs_dir: doc/

# Configuration
theme:
  name: 'material'
  logo: ''
  favicon: ''
  palette:
    primary: 'white'
  features:
    - navigation.top
    - header.autohide
  language: 'zh'

 
nav:

  - Home: README.md

  - 介绍:
    - 什么是Ehoney: Introduction/WEhoney.md
    - 名词解释: Introduction/Glossary.md
    - 快速开始: Introduction/QuickStart.md
    - 使用说明: Introduction/Description.md
    - 项目架构: Introduction/Architecture.md
    - 常见问题: Introduction/CommonProblem.md
    - 贡献者: Introduction/Contributor.md
  - 入门: 
    - 生产安装: GetStart/ProductionSafety.md
    - 模拟攻击: GetStart/SimulatedAttack.md
    - 社区参与: GetStart/Community.md
  - 教程: 
    - 构建密网: Tutorials/HoneyNet.md
    - 诱饵: Tutorials/HoneyBait.md
    - 密签: Tutorials/HoneyPot.md
    - 伪装代理: Tutorials/CamouflageAgent.md
    - 协议代理: Tutorials/AgreementAgency.md 
    - 云原生支持: Tutorials/CloudNativeSupport.md
    - 探针Agent:  Tutorials/ProbeAgent.md
    - 样本捕获与告警: Tutorials/SampleCaptureAndAlert.md
  - 定制化指南:
    - 协议代理自定义: CustomizedGuide/ProtocolAgent.md
    - 容器自定义: CustomizedGuide/Docker.md
    - 自定义harbo:  CustomizedGuide/Harbo.md
  - 参考手册:
    - 1.0版本: ReferenceBook/Version1.0.md
    - 测试用例v1.0: ReferenceBook/TestCase1.0.md
  - pdf: pdf/Ehoney.pdf

markdown_extensions:
  - footnotes
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
#      toc_depth: 3
      permalink: true
      separator: "_"
  - mdx_truly_sane_lists
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

static_templates:
  - index.html

# Plugins
plugins:
  - macros
  - git-revision-date-localized
  - with-pdf:
      copyright: 
      cover_subtitle:  
      author:  
      cover: true
      back_cover: true
      cover_logo: './img/logo_ehoney_black.svg'
      output_path: pdf/Ehoney.pdf
      show_anchors: true
      toc_level: 2

extra_javascript:
  - js/version-select.js
  - js/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

#google_analytics:
#  - UA-12345-78
#  - auto
