# Project information
site_name: Ehoney欺骗防御系统
site_description: 
site_author: 
docs_dir: doc/

# Configuration
theme:
  name: 'material'
  logo: ''
  favicon: ''
  palette:
    primary: 'white'
  features:
    - navigation.top
    - header.autohide
  language: 'zh'

 
nav:

  - 介绍:
    - 什么是Ehoney: 什么是Ehoney.md
    - 名词解释: 名词解释.md
    - 快速开始: 快速开始.md
    - 使用说明: 使用说明.md
    - 项目架构: 项目架构.md
    - 常见问题: 常见问题.md
    - 贡献者: 贡献者.md
  - 入门: 
    - 生产安装: 生产安装.md
    - 模拟攻击: 模拟攻击.md
    - 社区参与: 社区参与.md
  - 教程: 
    - 构建密网: 构建密网.md
    - 诱饵: 诱饵.md
    - 密签: 密签.md
    - 伪装代理: 伪装代理.md
    - 协议代理: 协议代理.md
    - 云原生支持: 云原生支持.md
    -  探针Agent:  探针Agent.md
    - 样本捕获与告警: 样本捕获与告警.md
  - 定制化指南:
    - 协议代理自定义: 协议代理自定义.md
    - 容器自定义: 容器自定义.md
    -  自定义harbo:  自定义harbo.md
  - 参考手册:
    - 1.0版本: 1.0版本.md
    - 测试用例v1.0: 测试用例v1.0.md
  - pdf: pdf/Ehoney.pdf

markdown_extensions:
  - footnotes
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
#      toc_depth: 3
      permalink: true
      separator: "_"
  - mdx_truly_sane_lists
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

static_templates:
  - 404.html

# Plugins
plugins:
  - macros
  - git-revision-date-localized
  - with-pdf:
      copyright: 
      cover_subtitle:  
      author:  
      cover: true
      back_cover: true
      cover_logo: './img/logo_ehoney_black.svg'
      output_path: pdf/Ehoney.pdf
      show_anchors: true
      toc_level: 2

extra_javascript:
  - js/version-select.js
  - js/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

#google_analytics:
#  - UA-12345-78
#  - auto
