# Project information
site_name: Ehoney欺骗防御系统
site_description: 
site_author: 
docs_dir: doc/

# Configuration
theme:
  name: 'material'
  logo: ''
  favicon: ''
  palette:
    primary: 'white'
  features:
    - navigation.top
    - header.autohide
  language: 'zh'

 
nav:

  - 介绍:
    - 什么是Ehoney: doc/Introduction/WEhoney.md
    - 名词解释: doc/Introduction/Glossary.md
    - 快速开始: doc/Introduction/QuickStart.md
    - 使用说明: doc/Introduction/Description.md
    - 项目架构: doc/Introduction/Architecture.md
    - 常见问题: doc/Introduction/CommonProblem.md
    - 贡献者: doc/Introduction/Contributor.md
  - 入门: 
    - 生产安装: doc/GetStart/ProductionSafety.md
    - 模拟攻击: doc/GetStart/SimulatedAttack.md
    - 社区参与: doc/GetStart/Community.md
  - 教程: 
    - 构建密网: doc/Tutorials/HoneyNet.md
    - 诱饵: doc/Tutorials/HoneyBait.md
    - 密签: doc/Tutorials/HoneyPot.md
    - 伪装代理: doc/Tutorials/CamouflageAgent.md
    - 协议代理: doc/Tutorials/AgreementAgency.md 
    - 云原生支持: doc/Tutorials/CloudNativeSupport.md
    - 探针Agent:  doc/Tutorials/ProbeAgent.md
    - 样本捕获与告警: doc/Tutorials/SampleCaptureAndAlert.md
  - 定制化指南:
    - 协议代理自定义: doc/CustomizedGuide/ProtocolAgent.md
    - 容器自定义: doc/CustomizedGuide/Docker.md
    - 自定义harbo:  doc/CustomizedGuide/Harbo.md
  - 参考手册:
    - 1.0版本: doc/ReferenceBook/Version1.0.md
    - 测试用例v1.0: doc/ReferenceBook/TestCase1.0.md
  - pdf: pdf/Ehoney.pdf

markdown_extensions:
  - footnotes
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
#      toc_depth: 3
      permalink: true
      separator: "_"
  - mdx_truly_sane_lists
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

static_templates:
  - 404.html

# Plugins
plugins:
  - macros
  - git-revision-date-localized
  - with-pdf:
      copyright: 
      cover_subtitle:  
      author:  
      cover: true
      back_cover: true
      cover_logo: './img/logo_ehoney_black.svg'
      output_path: pdf/Ehoney.pdf
      show_anchors: true
      toc_level: 2

extra_javascript:
  - js/version-select.js
  - js/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

#google_analytics:
#  - UA-12345-78
#  - auto
